image: maven:3.6.3-jdk-11

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
